const actionTypes = {
  GET_ITEMS: `GET_ITEMS`,
  GET_ITEM: `GET_ITEM`,
  ADD_ITEM: `ADD_ITEM`,
  EDIT_ITEM: `EDIT_ITEM`,
  TOGGLE_MODAL: `TOGGLE_MODAL`,
  TOGGLE_DELETE_MODAL: `TOGGLE_DELETE_MODAL`,
  SORT_BY_DISTANCE: `SORT_BY_DISTANCE`,
  SORT_BY_DATE: `SORT_BY_DATE`,
  DELETE_ITEM: `DELETE_ITEM`,
};

export { actionTypes };
